// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include <fstream>
#include <iostream>
#include <regex>
#include <sstream>
#include <string>

std::string ReadPackageVersion(const std::string& package_json_path) {
  std::ifstream file(package_json_path);
  if (!file.is_open()) {
    std::cerr << "Error: Could not open " << package_json_path << std::endl;
    exit(1);
  }

  std::stringstream buffer;
  buffer << file.rdbuf();
  std::string content = buffer.str();

  // Simple regex to extract version field from package.json
  std::regex version_regex(R"#("version"\s*:\s*"([^"]+)")#");
  std::smatch match;

  if (std::regex_search(content, match, version_regex)) {
    return match[1].str();
  }

  std::cerr << "Error: Could not find version in " << package_json_path
            << std::endl;
  exit(1);
}

void GenerateHeaderFile(const std::string& output_path,
                        const std::string& version) {
  std::ofstream file(output_path);
  if (!file.is_open()) {
    std::cerr << "Error: Could not write to " << output_path << std::endl;
    exit(1);
  }

  file << "// Generated by generate-version-header.cc\n"
       << "#ifndef PROTOBUF_JAVASCRIPT_VERSION_H__\n"
       << "#define PROTOBUF_JAVASCRIPT_VERSION_H__\n"
       << "\n"
       << "const char* const kProtobufJavascriptVersion = \"" << version
       << "\";\n"
       << "\n"
       << "#endif  // PROTOBUF_JAVASCRIPT_VERSION_H__\n";
}

int main(int argc, char* argv[]) {
  if (argc != 3) {
    std::cerr << "Usage: " << argv[0] << " <package_json_path> <output_header_path>" << std::endl;
    return 1;
  }

  std::string package_json_path = argv[1];
  std::string output_path = argv[2];

  std::string version = ReadPackageVersion(package_json_path);
  GenerateHeaderFile(output_path, version);

  std::cout << "Generated " << output_path << " with version " << version
            << std::endl;

  return 0;
}
